version: "3.2"
services:
  php:
    build: './php-docker/'

    networks:
      - backend
    volumes:
      - ./:/var/www/html/
   
  apache:
    build: './apache/'
    depends_on:
      - mysql
      - php
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/

  mysql:
    image: mysql:5.6.40
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
   
    environment:
      MYSQL_DATABASE: 'notice'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'


    

    
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '9906:3306'
    expose:
      # Opens port 3306 on the container
      - '9906'
      # Where our data will be persisted

    networks:
      - backend
   
networks:
  frontend:
  backend:
